### PR TITLE
Return empty object if instance is None

### PR DESCRIPTION
**Pull request by mishrag**
If passed a `None` instance to the serializer, DRF returns an object with default field values.

So for the class defined below:

```python
class TestDoc(RPDocumentBase):
    field1 = fields.BooleanField(default=False)
    field2 = fields.IntField(default=1)
```

`self.get_serializer(instance=None).data` will return `{field1: false, field2: 1}` to the FE. So `_.isEmpty(returnedObject)` on the FE fails unexpectedly. Instead the FE has to check `_.isNil(returnedObject.id)`. We can check if any FE code is doing the latter before deploying this change.

### CODE REVIEW

**Comment by myprasanna** [comment]
I'm not sure, one is right or one is wrong. This is a risky change obviously and can't be merged as is.

What specific case are you running into?

**Comment by sauravshah** [comment]
@mishrag @myprasanna we should probably block creating a serializer with instance=None. That would point towards some other issue in code - should have been a 404 or needs to be gracefully handled case by case. We can do this in RPDocumentSerializer rather than change DRF.

**Comment by mishrag** [comment]
Specific case in `PayScheduleViewSet`:

```
serializer = self.get_serializer(instance=role.paySchedule, many=False)
return Response(serializer.data, status=status.HTTP_200_OK)
```

`role.paySchedule` can be `None` and the front end now has to check for `response.id` in place of just checking if the response is empty.

I am writing a workaround for this in the ViewSet itself until we decide on the final solution.

**Comment by myprasanna** [comment]
The initialization with None isn't always bad. That is what makes embedded documents get created with default values when front-end doesn't send anything. We should leave it as is and not call with None IMO right now, but not a 100%; If we see there are more places breaking with this assumption and it's non-obvious we can change it..

**Comment by mishrag** [comment]
I think this change shouldn't affect creation of embedded documents with default values because it does not touch `to_internal_value`. I can double check that.

It's just that I found this behaviour (not returning an empty object) surprising. I think other people tripped here as well. For now, we can definitely leave this as it. I've also modified my code to special-case `None`.

**Comment by myprasanna** [comment]
:+1:

**Pull request closed without merging**
